version: '3.4'
services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
  db:
    build: ./DB
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  front-app:
    build:
      context: ./FRONT/front-app
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
volumes:
  pgdata: