name: Python - Pytest

on:
    push:
        # Temporary disabled for testing
        # paths:
        #     - "API/**"
    workflow_dispatch:

jobs:
    pytest:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: admin_pass
                    POSTGRES_USER: admin_user
                    POSTGRES_DB: ioproject_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r ./API/requirements.txt
            - name: Test with pytest
              run: |
                  pip install pytest pytest-cov
                  pytest ./API/ --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=api | tee pytest-coverage.txt
            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@main
              with:
                  pytest-coverage-path: ./pytest-coverage.txt
                  junitxml-path: ./pytest.xml
                  default-branch: ${{ github.ref_name }}
